// <auto-generated />
using System;
using DynamicTranslate.Demo.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicTranslate.Demo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626131418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DynamicTranslate.DB.OverrideTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entity")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Property")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(3500)
                        .HasColumnType("nvarchar(3500)");

                    b.HasKey("Id");

                    b.HasIndex("Text");

                    b.HasIndex("Entity", "Property", "Key", "LanguageCode")
                        .IsUnique()
                        .HasFilter("[Entity] IS NOT NULL AND [Property] IS NOT NULL AND [Key] IS NOT NULL AND [LanguageCode] IS NOT NULL");

                    b.ToTable("OverrideTranslations", "Translation");
                });

            modelBuilder.Entity("DynamicTranslate.DB.OverrideTranslationDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("OverrideTranslationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(3500)
                        .HasColumnType("nvarchar(3500)");

                    b.HasKey("Id");

                    b.HasIndex("OverrideTranslationId");

                    b.ToTable("OverrideTranslationDetails", "Translation");
                });

            modelBuilder.Entity("DynamicTranslate.Demo.Domain.LookupCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("LookupCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "books"
                        });
                });

            modelBuilder.Entity("DynamicTranslate.Demo.Domain.LookupDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("LookupDetails");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MasterId = 1L,
                            Name = "Clean Code: A Handbook of Agile Software Craftsmanship"
                        },
                        new
                        {
                            Id = 2L,
                            MasterId = 1L,
                            Name = "Design Patterns: Elements of Reusable Object-Oriented Software"
                        },
                        new
                        {
                            Id = 5L,
                            MasterId = 1L,
                            Name = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = 6L,
                            MasterId = 1L,
                            Name = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 7L,
                            MasterId = 1L,
                            Name = "Computer Networking: A Top-Down Approach"
                        },
                        new
                        {
                            Id = 3L,
                            MasterId = 2L,
                            Name = "Quantum Physics"
                        },
                        new
                        {
                            Id = 4L,
                            MasterId = 2L,
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 8L,
                            MasterId = 2L,
                            Name = "The Feynman Lectures on Physics"
                        },
                        new
                        {
                            Id = 9L,
                            MasterId = 2L,
                            Name = "Introduction to Quantum Mechanics"
                        },
                        new
                        {
                            Id = 10L,
                            MasterId = 2L,
                            Name = "Classical Mechanics"
                        },
                        new
                        {
                            Id = 11L,
                            MasterId = 2L,
                            Name = "Thermodynamics and Statistical Mechanics"
                        },
                        new
                        {
                            Id = 12L,
                            MasterId = 3L,
                            Name = "Calculus: Early Transcendentals"
                        },
                        new
                        {
                            Id = 13L,
                            MasterId = 3L,
                            Name = "Linear Algebra and Its Applications"
                        },
                        new
                        {
                            Id = 14L,
                            MasterId = 3L,
                            Name = "Probability and Statistics"
                        },
                        new
                        {
                            Id = 15L,
                            MasterId = 3L,
                            Name = "Discrete Mathematics and Its Applications"
                        },
                        new
                        {
                            Id = 16L,
                            MasterId = 4L,
                            Name = "Molecular Biology of the Cell"
                        },
                        new
                        {
                            Id = 17L,
                            MasterId = 4L,
                            Name = "Genetics: Analysis of Genes and Genomes"
                        },
                        new
                        {
                            Id = 18L,
                            MasterId = 4L,
                            Name = "Ecology: Concepts and Applications"
                        },
                        new
                        {
                            Id = 19L,
                            MasterId = 5L,
                            Name = "Sapiens: A Brief History of Humankind"
                        },
                        new
                        {
                            Id = 20L,
                            MasterId = 5L,
                            Name = "The History of the Ancient World"
                        },
                        new
                        {
                            Id = 21L,
                            MasterId = 5L,
                            Name = "A People's History of the United States"
                        });
                });

            modelBuilder.Entity("DynamicTranslate.Demo.Domain.LookupMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("LookupMasters");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1L,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 1L,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 1L,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 1L,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("DynamicTranslate.DB.OverrideTranslationDetail", b =>
                {
                    b.HasOne("DynamicTranslate.DB.OverrideTranslation", "OverrideTranslation")
                        .WithMany("OverrideTranslationDetails")
                        .HasForeignKey("OverrideTranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OverrideTranslation");
                });

            modelBuilder.Entity("DynamicTranslate.Demo.Domain.LookupDetail", b =>
                {
                    b.HasOne("DynamicTranslate.Demo.Domain.LookupMaster", "Master")
                        .WithMany("LookupDetails")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("DynamicTranslate.Demo.Domain.LookupMaster", b =>
                {
                    b.HasOne("DynamicTranslate.Demo.Domain.LookupCategory", "Category")
                        .WithMany("LookupMasters")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DynamicTranslate.DB.OverrideTranslation", b =>
                {
                    b.Navigation("OverrideTranslationDetails");
                });

            modelBuilder.Entity("DynamicTranslate.Demo.Domain.LookupCategory", b =>
                {
                    b.Navigation("LookupMasters");
                });

            modelBuilder.Entity("DynamicTranslate.Demo.Domain.LookupMaster", b =>
                {
                    b.Navigation("LookupDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
