<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Title>Dynamic i18n Translate</Title>
    <Authors>Mustafa kamal</Authors>
    <Copyright>copyright 2024 for mustafa kamal</Copyright>
    <Description>Translate Netesd Poco objects content at run time</Description>
    <PackageProjectUrl>https://github.com/engmustafak26/DynamicTranslate</PackageProjectUrl>
    <PackageIcon>icon</PackageIcon>
    <RepositoryUrl>https://github.com/engmustafak26/DynamicTranslate</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>1.7.6</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icon" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GTranslate" Version="2.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.32" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Net.Http.Json" Version="10.0.9" />
  </ItemGroup>

</Project>
